# Generated by Django 4.2.3 on 2023-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecreamtype',
            name='price',
        ),
        migrations.AlterField(
            model_name='icecreamtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
