# Generated by Django 4.2.3 on 2023-08-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_types', '0002_remove_icecreamtype_price_alter_icecreamtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecreamtype',
            options={'verbose_name': 'Ice cream type', 'verbose_name_plural': 'Ice cream types'},
        ),
    ]
