services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ice_cream_erp
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata-ice_cream_erp:/var/lib/postgresql/data/pgdata
    expose:
        - "5432"
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  pgdata-ice_cream_erp:

