# Generated by Django 4.2.3 on 2023-07-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_icecream_id_alter_icecream_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_rainy', models.BooleanField(default=False)),
                ('stores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='stores.icecream')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.report')),
            ],
        ),
    ]
