# Generated by Django 4.2.3 on 2023-07-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_icecream_stores_icecream_store'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='stores',
        ),
        migrations.AddField(
            model_name='report',
            name='cones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='cups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stores.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.report'),
        ),
    ]
