# Generated by Django 4.2.3 on 2023-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_stores_report_cones_report_cups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
