# Generated by Django 4.2.3 on 2023-08-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_icecream_options_alter_store_options_and_more'),
        ('reports', '0003_report_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportitem',
            options={'verbose_name': 'Report item', 'verbose_name_plural': 'Report items'},
        ),
        migrations.AlterField(
            model_name='report',
            name='cones',
            field=models.IntegerField(default=0, verbose_name='Cones'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cups',
            field=models.IntegerField(default=0, verbose_name='Cups'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_rainy',
            field=models.BooleanField(default=False, verbose_name='Rainy'),
        ),
        migrations.AlterField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='report',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='ice_cream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='stores.icecream', verbose_name='Ice cream'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.report', verbose_name='Report'),
        ),
    ]
