# Generated by Django 4.2.3 on 2023-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_options_alter_reportitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='need_refill',
            field=models.BooleanField(default=False, verbose_name='Need refill'),
        ),
    ]
