# Generated by Django 4.2.3 on 2023-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default="ice_cream_erp's Ice Cream", max_length=100, unique=True),
        ),
    ]
