# Generated by Django 4.2.3 on 2023-07-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='stores',
        ),
        migrations.AddField(
            model_name='icecream',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='stores.store'),
            preserve_default=False,
        ),
    ]
