# Generated by Django 4.2.3 on 2023-07-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_types', '0001_initial'),
        ('stores', '0004_remove_icecream_stores_icecream_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='ice_cream_types.icecreamtype'),
        )
    ]
