# Generated by Django 4.2.3 on 2023-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_icecream_id_alter_icecream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
