# Generated by Django 4.2.3 on 2023-08-01 21:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ice_cream_types', '0003_alter_icecreamtype_options'),
        ('stores', '0006_icecream_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'verbose_name': 'Ice Cream', 'verbose_name_plural': 'Ice Creams'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='icecream',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='ice_cream_types.icecreamtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cones',
            field=models.IntegerField(verbose_name='Cones'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cups',
            field=models.IntegerField(verbose_name='Cups'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default="ice_cream_erp's Ice Cream", max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
    ]
